// 反応式組み立てクイズ用データ
// a + b → target（順番はどちらでも正解）
// distractorsA / distractorsB は各3つ（正解と合わせて4択）

const QUIZ_ELEMENTARY = [
  { target: "水", a: "H₂", b: "O₂", distractorsA: ["N₂", "CO₂", "He"], distractorsB: ["Cl₂", "N₂", "CO"], explanation: "水は水素と酸素がくっつくだけ！地球の7割はこれ。君の体もほとんど水だよ。" },
  { target: "二酸化炭素", a: "C", b: "O₂", distractorsA: ["H₂", "N₂", "S"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "息を吐くと出てくる気体。植物はこれを吸って成長する、空気のリサイクル係！" },
  { target: "一酸化炭素", a: "C", b: "O", distractorsA: ["H₂", "N₂", "Fe"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "酸素が足りないとできる危険な気体。ストーブの換気を忘れると怖いのはこれ。" },
  { target: "アンモニア", a: "N₂", b: "H₂", distractorsA: ["O₂", "CO₂", "Cl₂"], distractorsB: ["O₂", "Cl₂", "CO"], explanation: "ツンとするにおいの正体。トイレの洗剤にも仲間がいる。肥料にも変身する！！" },
  { target: "塩化ナトリウム（食塩）", a: "Na", b: "Cl₂", distractorsA: ["K", "Ca", "Mg"], distractorsB: ["O₂", "H₂", "N₂"], explanation: "しょっぱさの王様・食塩！海の水を蒸発させると出てくる、暮らしの相棒。" },
  { target: "メタン", a: "C", b: "H₂", distractorsA: ["O₂", "N₂", "S"], distractorsB: ["O₂", "Cl₂", "N₂"], explanation: "天然ガスの主役。コンロの火を灯すとき、見えないところで燃えているよ。" },
  { target: "塩酸", a: "H₂", b: "Cl₂", distractorsA: ["O₂", "N₂", "CO₂"], distractorsB: ["O₂", "N₂", "F₂"], explanation: "強い酸の代表。胃の中にもちょっとある。金属を溶かすパワーがある！" },
  { target: "硫化水素", a: "H₂", b: "S", distractorsA: ["O₂", "N₂", "C"], distractorsB: ["O₂", "Cl₂", "N₂"], explanation: "腐った卵くさい気体。温泉のにおいの正体のひとつ。鼻がツンとするやつ！" },
  { target: "二酸化硫黄", a: "S", b: "O₂", distractorsA: ["C", "N₂", "H₂"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "火山ガスにも含まれる刺激臭の気体。昔はマッチのにおいでもおなじみ。" },
  { target: "酸化マグネシウム", a: "Mg", b: "O₂", distractorsA: ["Fe", "Cu", "Zn"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "マグネシウムを燃やすと真っ白な粉に！花火のキラキラ光の影の主役。" },
  { target: "酸化鉄（さび）", a: "Fe", b: "O₂", distractorsA: ["Cu", "Al", "Zn"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "鉄が赤くさびる正体。自転車を雨ざらしにすると増える、あの茶色い粉！" },
  { target: "酸化銅", a: "Cu", b: "O₂", distractorsA: ["Fe", "Zn", "Ag"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "銅が黒っぽくなるとこれ。銅線や十円玉の表面変化のヒミツ。" },
  { target: "二酸化炭素（炭酸）", a: "CO", b: "O₂", distractorsA: ["H₂", "N₂", "NO"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "一酸化炭素に酸素を足すと二酸化炭素に。コーラのシュワシュワの材料！" },
  { target: "水（過酸化水素から）", a: "H₂O₂", b: "MnO₂", distractorsA: ["H₂O", "HCl", "NaCl"], distractorsB: ["Fe₂O₃", "CuO", "CaCO₃"], explanation: "オキシドールに二酸化マンガンを入れるとブクブク！酸素が発生して水が残る実験だ。" },
  { target: "石灰水の白濁（炭酸カルシウム）", a: "Ca(OH)₂", b: "CO₂", distractorsA: ["NaOH", "HCl", "NaCl"], distractorsB: ["O₂", "H₂", "N₂"], explanation: "石灰水に息を吹きかけると白く濁る。息の中のCO₂を見つけるマジック！" },
  { target: "酸素", a: "KClO₃", b: "MnO₂", distractorsA: ["KCl", "NaCl", "CO₂"], distractorsB: ["Fe₂O₃", "CuO", "CaCO₃"], explanation: "塩素酸カリウムを熱して酸素ゲット！触媒のMnO₂が反応をスピーディーにする。" },
  { target: "水素", a: "Zn", b: "HCl", distractorsA: ["Cu", "Au", "Ag"], distractorsB: ["H₂O", "NaCl", "CO₂"], explanation: "亜鉛に塩酸をかけるとプクプク水素！風船を飛ばす夢の気体の作り方。" },
  { target: "塩素", a: "NaCl", b: "電気分解", distractorsA: ["H₂O", "CO₂", "NH₃"], distractorsB: ["加熱", "冷却", "ろ過"], explanation: "食塩水を電気分解すると塩素が出る。プールの消毒くさいにおいの親戚！" },
  { target: "酸化カルシウム（生石灰）", a: "CaCO₃", b: "加熱", distractorsA: ["CaCl₂", "CaSO₄", "NaCl"], distractorsB: ["冷却", "電気分解", "ろ過"], explanation: "石灰石を熱すると生石灰に変身。水をかけるとアツアツになる不思議粉！" },
  { target: "炭酸カルシウム", a: "CaO", b: "CO₂", distractorsA: ["CaCl₂", "NaOH", "MgO"], distractorsB: ["O₂", "H₂", "N₂"], explanation: "貝殻やチョークの主成分。石灰水が白く濁るのも、これができた証拠！" },
  { target: "酢酸（お酢）", a: "CH₃COOH", b: "H₂O（水溶液）", distractorsA: ["HCl", "H₂SO₄", "HNO₃"], distractorsB: ["NaCl", "CO₂", "O₂"], explanation: "お酢の酸っぱさの正体は酢酸。サラダにかける化学、それが君の食卓！" },
  { target: "エタノール（アルコール）", a: "C₂H₄", b: "H₂O", distractorsA: ["CH₄", "C₆H₁₂O₆", "CO₂"], distractorsB: ["O₂", "N₂", "HCl"], explanation: "エチレンに水をくっつけるとエタノール。消毒液やお酒の仲間だよ。" },
  { target: "グルコース（ブドウ糖）", a: "CO₂", b: "H₂O（光合成）", distractorsA: ["NaCl", "N₂", "O₂だけ"], distractorsB: ["O₂", "N₂", "H₂"], explanation: "植物が光でCO₂と水から作る甘い燃料。お菓子のエネルギーのもとに！" },
  { target: "オゾン", a: "O₂", b: "紫外線", distractorsA: ["N₂", "CO₂", "H₂"], distractorsB: ["赤外線", "音波", "磁力"], explanation: "酸素に強い光が当たるとオゾンに。空の高いところで紫外線をガードしてくれる！" },
  { target: "氷（固体の水）", a: "H₂O", b: "冷却", distractorsA: ["CO₂", "NaCl", "O₂"], distractorsB: ["加熱", "電気分解", "圧縮のみ"], explanation: "水を冷やすだけで氷。かき氷も化学！分子の並びが変わると硬くなる。" },
  { target: "ドライアイス", a: "CO₂", b: "冷却・圧縮", distractorsA: ["H₂O", "O₂", "N₂"], distractorsB: ["加熱", "電気分解", "ろ過"], explanation: "二酸化炭素をギュッと冷やすとドライアイス。霧が出るステージ演出の常連！" },
  { target: "石鹸の泡（イメージ）", a: "油脂", b: "NaOH", distractorsA: ["砂糖", "食塩", "水だけ"], distractorsB: ["HCl", "CO₂", "O₂"], explanation: "油と水酸化ナトリウムから石鹸ができる。手洗いの泡は化学反応の味方！" },
  { target: "錆びないメッキのイメージ（亜鉛）", a: "Fe", b: "Zn", distractorsA: ["Au", "Ag", "Cu"], distractorsB: ["O₂", "Cl₂", "H₂"], explanation: "鉄に亜鉛をかぶせるとさびにくい。ガードレールの銀色、あれがメッキ！" },
  { target: "窒素酸化物（NO）", a: "N₂", b: "O₂", distractorsA: ["H₂", "Cl₂", "CO₂"], distractorsB: ["H₂", "Cl₂", "He"], explanation: "雷や高温で窒素と酸素がくっつくことも。空気はただ混ざってるだけじゃない！" },
  { target: "水蒸気", a: "H₂O", b: "加熱", distractorsA: ["CO₂", "O₂", "N₂"], distractorsB: ["冷却", "ろ過", "電気分解"], explanation: "お湯がグツグツすると水蒸気。見えない気体になって空へ旅立つ水！" },
];

const QUIZ_JUNIOR = [
  // —— 身近＋中学定番 ——
  { target: "水", a: "H₂", b: "O₂", distractorsA: ["N₂", "Cl₂", "CO"], distractorsB: ["N₂", "Cl₂", "CO₂"], explanation: "2H₂+O₂→2H₂O。水素爆弾の逆で、水は平和の化合物。宇宙でも見つかる定番！" },
  { target: "二酸化炭素", a: "C", b: "O₂", distractorsA: ["Si", "S", "P"], distractorsB: ["H₂", "N₂", "Cl₂"], explanation: "炭素が完全燃焼するとCO₂。ドライアイスも炭酸飲料のシュワも、こいつの変身だ。" },
  { target: "一酸化炭素", a: "C", b: "½O₂", distractorsA: ["Fe", "S", "N₂"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "酸素不足だとCOに。無色無臭で危険。古いストーブの換気は命を守る化学！" },
  { target: "アンモニア", a: "N₂", b: "H₂", distractorsA: ["O₂", "Cl₂", "CO₂"], distractorsB: ["O₂", "Cl₂", "F₂"], explanation: "ハーバー・ボッシュ法で大量生産。世界の食料を支える、においツンの英雄！" },
  { target: "塩化水素（塩酸の元）", a: "H₂", b: "Cl₂", distractorsA: ["O₂", "N₂", "F₂"], distractorsB: ["O₂", "N₂", "Br₂"], explanation: "水素と塩素は光でも反応。水に溶けると塩酸になる、酸の入り口！" },
  { target: "メタン", a: "C", b: "2H₂", distractorsA: ["Si", "S", "P"], distractorsB: ["O₂", "N₂", "Cl₂"], explanation: "最単純の炭化水素。沼の泡や天然ガスの主役で、温室効果でも話題の気体。" },
  { target: "エチレン", a: "C₂H₆", b: "脱水素", distractorsA: ["CH₄", "C₃H₈", "C₂H₂"], distractorsB: ["加水", "燃焼", "中和"], explanation: "果物を追熟させる気体。バナナとリンゴを一緒にすると早く熟すのはこれ！" },
  { target: "エタノール", a: "C₂H₄", b: "H₂O", distractorsA: ["CH₄", "CO₂", "C₆H₆"], distractorsB: ["HCl", "NaOH", "O₂"], explanation: "エチレンに水を付加するとエタノール。消毒液や燃料にもなる万能選手。" },
  { target: "硫酸", a: "SO₃", b: "H₂O", distractorsA: ["SO₂", "H₂S", "S"], distractorsB: ["HCl", "NaOH", "O₂"], explanation: "濃硫酸は脱水のプロ。バッテリー液にもいる、工業のキング・オブ・酸！" },
  { target: "硝酸", a: "NO₂", b: "H₂O・O₂", distractorsA: ["NH₃", "N₂", "NO"], distractorsB: ["HCl", "NaCl", "CO₂"], explanation: "肥料や爆薬の原料。オストワルト法でアンモニアから作られる強酸だ。" },
  { target: "水酸化ナトリウム", a: "Na", b: "H₂O", distractorsA: ["K", "Ca", "Mg"], distractorsB: ["HCl", "CO₂", "O₂"], explanation: "苛性ソーダ！石鹸作りや排水管クリーナーの強アルカリ。触ると危険、取り扱い注意。" },
  { target: "水酸化カルシウム", a: "CaO", b: "H₂O", distractorsA: ["CaCl₂", "CaCO₃", "Na₂O"], distractorsB: ["HCl", "CO₂", "O₂"], explanation: "生石灰に水→消石灰。石灰水の正体で、CO₂キャッチの実験スター。" },
  { target: "炭酸ナトリウム", a: "NaOH", b: "CO₂", distractorsA: ["NaCl", "NaNO₃", "KCl"], distractorsB: ["O₂", "H₂", "N₂"], explanation: "ソーダ灰。ガラスや洗剤づくりの相棒。重曹を熱しても仲間が出てくる。" },
  { target: "炭酸水素ナトリウム（重曹）", a: "Na₂CO₃", b: "CO₂・H₂O", distractorsA: ["NaCl", "NaOH", "K₂CO₃"], distractorsB: ["O₂", "H₂", "Cl₂"], explanation: "お菓子作りで生地をふくらませる魔法の粉。熱するとCO₂が出てパンが膨らむ！" },
  { target: "塩化アンモニウム", a: "NH₃", b: "HCl", distractorsA: ["N₂", "NO₂", "H₂"], distractorsB: ["H₂SO₄", "HNO₃", "H₂O"], explanation: "乾電池の中にもいる塩。アンモニアと塩酸の白煙実験、教室の定番ドラマ！" },
  { target: "硫酸銅（青色結晶）", a: "CuO", b: "H₂SO₄", distractorsA: ["Cu", "CuCl₂", "FeO"], distractorsB: ["HCl", "HNO₃", "H₂O"], explanation: "美しい青い結晶。電気めっきや実験で大活躍。乾くと白っぽくなるよ。" },
  { target: "塩化鉄(III)", a: "Fe", b: "Cl₂", distractorsA: ["Cu", "Zn", "Al"], distractorsB: ["O₂", "H₂", "N₂"], explanation: "プリント基板のエッチングにも使われる。鉄と塩素のガチ反応！" },
  { target: "酸化アルミニウム", a: "Al", b: "O₂", distractorsA: ["Fe", "Cu", "Zn"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "アルミの表面を守る透明の鎧。ルビーやサファイアの主成分でもある！" },
  { target: "二酸化ケイ素", a: "Si", b: "O₂", distractorsA: ["C", "Ge", "S"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "砂やガラスの主成分。スマホのガラスも、もとをたどれば砂の化学！" },
  { target: "酸化亜鉛", a: "Zn", b: "O₂", distractorsA: ["Fe", "Cu", "Pb"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "日焼け止めの白い粉の仲間。紫外線ガードは鉱物パワー！" },
  // —— 酸化物 ——
  { target: "酸化カルシウム", a: "Ca", b: "O₂", distractorsA: ["Mg", "Ba", "Na"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "生石灰。水をかけると発熱する危険＆便利アイテム。乾燥剤にもなる。" },
  { target: "酸化マグネシウム", a: "Mg", b: "O₂", distractorsA: ["Ca", "Zn", "Fe"], distractorsB: ["H₂", "N₂", "Cl₂"], explanation: "マグネシウム燃焼の白い灰。胃薬にも使われる、意外と身近な酸化物。" },
  { target: "酸化鉄(III)（赤鉄鉱）", a: "Fe", b: "O₂", distractorsA: ["Cu", "Ni", "Cr"], distractorsB: ["H₂", "S", "Cl₂"], explanation: "赤い鉄さび・赤鉄鉱。火星が赤いのも酸化鉄のせい、というロマン！" },
  { target: "四酸化三鉄（磁鉄鉱）", a: "3Fe", b: "2O₂", distractorsA: ["2Fe", "Fe", "4Fe"], distractorsB: ["O₂", "3O₂", "H₂O"], explanation: "マグネタイト。磁石にくっつく黒い鉱物。古代のコンパスの材料！" },
  { target: "酸化銅(II)", a: "Cu", b: "O₂", distractorsA: ["Ag", "Au", "Zn"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "黒い粉のCuO。水素で還元すると赤い銅が復活する、精錬ミニ実験。" },
  { target: "二酸化マンガン", a: "Mn", b: "O₂", distractorsA: ["Fe", "Cu", "Zn"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "乾電池の中の黒いやつ。酸素発生の触媒としても教室の人気者。" },
  { target: "二酸化チタン", a: "Ti", b: "O₂", distractorsA: ["Zn", "Fe", "Sn"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "白い顔料の王様。ペンキも日焼け止めも、この白色パワー！" },
  { target: "酸化クロム(III)", a: "Cr", b: "O₂", distractorsA: ["Mn", "Fe", "Ni"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "鮮やかな緑の顔料。お金のインクや塗料で見たことある色かも。" },
  { target: "一酸化窒素", a: "N₂", b: "O₂", distractorsA: ["H₂", "Cl₂", "CO₂"], distractorsB: ["H₂", "Cl₂", "F₂"], explanation: "高温で空気の窒素と酸素が反応。車の排ガスにも関わる気体。" },
  { target: "二酸化窒素", a: "NO", b: "O₂", distractorsA: ["N₂", "NH₃", "N₂O"], distractorsB: ["H₂", "Cl₂", "CO₂"], explanation: "赤褐色の気体。大気汚染のニュースで名前を聞く、あのNO₂！" },
  // —— 酸・塩基 ——
  { target: "リン酸", a: "P₄O₁₀", b: "H₂O", distractorsA: ["P", "PH₃", "PO₄"], distractorsB: ["HCl", "NaOH", "O₂"], explanation: "コーラの酸味や肥料に関係。骨やDNAにもリンは不可欠！" },
  { target: "炭酸", a: "CO₂", b: "H₂O", distractorsA: ["CO", "C", "CH₄"], distractorsB: ["HCl", "NaOH", "O₂"], explanation: "シュワシュワの正体の一部。弱い酸だけど、石灰水を白く濁らせる実力者。" },
  { target: "水酸化カリウム", a: "K", b: "H₂O", distractorsA: ["Na", "Ca", "Mg"], distractorsB: ["HCl", "CO₂", "O₂"], explanation: "KOH。液体石鹸やアルカリ電池で活躍する強塩基。" },
  { target: "アンモニア水", a: "NH₃", b: "H₂O", distractorsA: ["N₂", "NO₂", "H₂"], distractorsB: ["HCl", "NaCl", "O₂"], explanation: "アンモニアが水に溶けると弱い塩基に。ガラス拭きスプレーのツンの元。" },
  { target: "酢酸エチル（エステル）", a: "CH₃COOH", b: "C₂H₅OH", distractorsA: ["HCl", "NaOH", "H₂SO₄"], distractorsB: ["CH₄", "H₂O", "CO₂"], explanation: "フルーティーなにおいのエステル。マニキュア除光液の香りに近い！" },
  { target: "塩化銀", a: "AgNO₃", b: "NaCl", distractorsA: ["Ag", "Ag₂O", "CuCl₂"], distractorsB: ["NaOH", "Na₂CO₃", "KNO₃"], explanation: "白い沈殿！光に当たると黒ずむので、昔の写真フィルムの原理にも。" },
  { target: "硫酸バリウム", a: "BaCl₂", b: "Na₂SO₄", distractorsA: ["BaO", "BaCO₃", "CaCl₂"], distractorsB: ["NaCl", "NaOH", "KCl"], explanation: "胃のX線検査で飲むバリウムの仲間。水に溶けにくい白い沈殿。" },
  { target: "水酸化銅(II)", a: "CuSO₄", b: "NaOH", distractorsA: ["Cu", "CuO", "FeSO₄"], distractorsB: ["HCl", "NaCl", "CO₂"], explanation: "青いゼリー状の沈殿。加熱すると黒いCuOに変わる変身もの。" },
  { target: "硫化亜鉛", a: "Zn", b: "S", distractorsA: ["Fe", "Cu", "Pb"], distractorsB: ["O₂", "Cl₂", "N₂"], explanation: "蛍光塗料や螢光体の材料。暗いところで光るおもちゃのヒミツ！" },
  { target: "過酸化水素", a: "H₂", b: "O₂", distractorsA: ["H₂O", "HCl", "NH₃"], distractorsB: ["N₂", "Cl₂", "CO₂"], explanation: "オキシドールの主成分（H₂O₂）。分解すると酸素が出て、傷口でブクブクする！" },
  // —— 鉱物（多め） ——
  { target: "石英（水晶）", a: "Si", b: "O₂", distractorsA: ["C", "Al", "Fe"], distractorsB: ["H₂", "S", "Cl₂"], explanation: "SiO₂の宝石！時計の振動子やガラスの原料。透明な魔法の石。" },
  { target: "方解石（カルサイト）", a: "Ca", b: "CO₃²⁻", distractorsA: ["Mg", "Fe", "Na"], distractorsB: ["SO₄²⁻", "Cl⁻", "O₂"], explanation: "CaCO₃。塩酸をかけるとアワアワ！鍾乳洞のつららもこいつの積み重ね。" },
  { target: "マグネサイト", a: "Mg", b: "CO₃²⁻", distractorsA: ["Ca", "Fe", "Zn"], distractorsB: ["SO₄²⁻", "O₂", "S²⁻"], explanation: "MgCO₃。耐火レンガの材料。マグネシウムを取り出す鉱石ルートもある。" },
  { target: "ドロマイト（苦灰石）", a: "CaMg", b: "(CO₃)₂", distractorsA: ["CaFe", "NaK", "FeZn"], distractorsB: ["SO₄", "O₂", "S₂"], explanation: "カルシウムとマグネシウムの炭酸塩。山や建材でよく出会う鉱物。" },
  { target: "黄鉄鉱（パイライト）", a: "Fe", b: "S₂", distractorsA: ["Cu", "Pb", "Zn"], distractorsB: ["O₂", "Cl₂", "CO₃"], explanation: "愚者の金！金色に光るのに金じゃない。ストライク（筋）は黒いのが見分けポイント。" },
  { target: "黄銅鉱", a: "CuFe", b: "S₂", distractorsA: ["Cu₂", "Fe", "Pb"], distractorsB: ["O₂", "CO₃", "Cl₂"], explanation: "CuFeS₂。世界の銅の大半はここから。虹色に輝くかっこいい鉱石！" },
  { target: "方鉛鉱", a: "Pb", b: "S", distractorsA: ["Zn", "Fe", "Cu"], distractorsB: ["O₂", "Cl₂", "CO₃"], explanation: "PbS。重い！鉛の主鉱石で、昔は銀も一緒に取れたトレジャー鉱物。" },
  { target: "閃亜鉛鉱", a: "Zn", b: "S", distractorsA: ["Pb", "Fe", "Cu"], distractorsB: ["O₂", "Cl₂", "CO₃"], explanation: "ZnS。亜鉛の主鉱石。蛍光を示すものもあり、ブラックライトで光ることも！" },
  { target: "輝銀鉱", a: "Ag₂", b: "S", distractorsA: ["Ag", "Au", "Cu₂"], distractorsB: ["O₂", "Cl₂", "CO₃"], explanation: "Ag₂S。銀の鉱石。空気中で銀が黒ずむのも硫化銀のせい。" },
  { target: "辰砂（しんしゃ）", a: "Hg", b: "S", distractorsA: ["Pb", "Zn", "Fe"], distractorsB: ["O₂", "Cl₂", "CO₃"], explanation: "HgS。真っ赤な水銀の鉱石。古代の朱肉や顔料のルーツ！" },
  { target: "蛍石", a: "Ca", b: "F₂", distractorsA: ["Mg", "Ba", "Na"], distractorsB: ["Cl₂", "O₂", "S"], explanation: "CaF₂。紫外線で光る＝蛍光の語源！フッ素化学の入口でもある。" },
  { target: "石膏", a: "CaSO₄", b: "2H₂O", distractorsA: ["CaCO₃", "CaCl₂", "Na₂SO₄"], distractorsB: ["HCl", "CO₂", "O₂"], explanation: "ギプスや黒板のチョークの仲間。折れた骨を守る白いヒーロー。" },
  { target: "重晶石", a: "Ba", b: "SO₄", distractorsA: ["Ca", "Mg", "Sr"], distractorsB: ["CO₃", "S", "Cl₂"], explanation: "BaSO₄。重い！石油掘削泥水やX線造影でも活躍する産業鉱物。" },
  { target: "赤鉄鉱", a: "Fe₂", b: "O₃", distractorsA: ["Fe₃", "Fe", "FeO"], distractorsB: ["O₂", "O₄", "S₃"], explanation: "Fe₂O₃。鉄の主力鉱石。赤い土や火星の色の正体候補！" },
  { target: "磁鉄鉱", a: "Fe₃", b: "O₄", distractorsA: ["Fe₂", "Fe", "FeO"], distractorsB: ["O₃", "O₂", "S₄"], explanation: "Fe₃O₄。天然の磁石。古代人が方位を知るのに使った伝説の石。" },
  { target: "クロム鉄鉱", a: "FeCr₂", b: "O₄", distractorsA: ["Fe₂O₃", "Fe₃O₄", "Cr₂O₃"], distractorsB: ["S₄", "CO₃", "Cl₂"], explanation: "ステンレス鋼のクロム源。錆びないスプーンの陰の功労者。" },
  { target: "ボーキサイト（アルミ原料）", a: "Al₂O₃", b: "nH₂O", distractorsA: ["SiO₂", "Fe₂O₃", "CaCO₃"], distractorsB: ["CO₂", "SO₂", "Cl₂"], explanation: "アルミ缶のもとはこの鉱石。電気をたくさん使って金属アルミに精錬する！" },
  { target: "コランダム", a: "Al₂", b: "O₃", distractorsA: ["Si", "Fe₂", "Mg"], distractorsB: ["O₂", "S₃", "CO₃"], explanation: "ルビー（赤）もサファイア（青）も同じAl₂O₃！不純物が色を変える宝石マジック。" },
  { target: "スピネル", a: "Mg", b: "Al₂O₄", distractorsA: ["Fe", "Zn", "Ca"], distractorsB: ["SiO₄", "CO₃", "SO₄"], explanation: "MgAl₂O₄。歴史的な「ルビー」の一部は実はスピネルだった、というミステリーも。" },
  { target: "オリビン（かんらん石）", a: "(Mg,Fe)₂", b: "SiO₄", distractorsA: ["Ca₂", "Al₂", "Na₂"], distractorsB: ["CO₃", "SO₄", "O₂"], explanation: "マントルの主役級鉱物。宝石名はペリドット、黄緑が美しい！" },
  { target: "輝石", a: "CaMg", b: "Si₂O₆", distractorsA: ["NaAl", "KAl", "FeCu"], distractorsB: ["CO₃", "SO₄", "S₂"], explanation: "火成岩によくいる鎖状ケイ酸塩。玄武岩を割ると顔を出す常連。" },
  { target: "長石", a: "KAlSi₃", b: "O₈", distractorsA: ["CaCO₃", "SiO₂", "Fe₂O₃"], distractorsB: ["O₂", "CO₃", "S₈"], explanation: "地殻で一番多い鉱物グループ。陶磁器の原料にもなる、足元の王者。" },
  { target: "雲母（マイカ）", a: "KAl₂", b: "(AlSi₃O₁₀)(OH)₂", distractorsA: ["CaCO₃", "FeS₂", "SiO₂"], distractorsB: ["O₂", "Cl₂", "S"], explanation: "薄くはがれるキラキラ鉱物。昔の電気絶縁や化粧にも使われた。" },
  { target: "石榴石（ガーネット）", a: "Fe₃Al₂", b: "(SiO₄)₃", distractorsA: ["CaCO₃", "NaCl", "FeS₂"], distractorsB: ["CO₃", "SO₄", "O₂"], explanation: "誕生石にもなる深い赤。研磨剤としても優秀なケイ酸塩鉱物。" },
  { target: "トパーズ", a: "Al₂SiO₄", b: "(F,OH)₂", distractorsA: ["SiO₂", "Al₂O₃", "CaF₂"], distractorsB: ["Cl₂", "O₂", "S"], explanation: "フッ素を含む宝石。硬度が高く、ジュエリーの定番！" },
  { target: "ベリル（エメラルドの仲間）", a: "Be₃Al₂", b: "Si₆O₁₈", distractorsA: ["Mg₃Al₂", "Fe₃Al₂", "Ca₃Al₂"], distractorsB: ["CO₃", "SO₄", "O₂"], explanation: "エメラルドはベリル＋クロム。緑の王者はベリリウムの環状構造！" },
  { target: "オパール", a: "SiO₂", b: "nH₂O", distractorsA: ["Al₂O₃", "CaCO₃", "Fe₂O₃"], distractorsB: ["CO₂", "SO₂", "Cl₂"], explanation: "水を含んだシリカ。見る角度で色が変わる遊色効果はナノ構造の芸術！" },
  { target: "ダイヤモンド", a: "C", b: "超高圧・高温", distractorsA: ["Si", "Ge", "B"], distractorsB: ["冷却", "電気分解", "溶解"], explanation: "炭素が極限状態で結晶化。地球深部のプレッシャーが生む最高硬度！" },
  { target: "黒鉛（グラファイト）", a: "C", b: "層状構造", distractorsA: ["Si", "Fe", "S"], distractorsB: ["立方晶", "気体化", "イオン結合"], explanation: "同じ炭素なのに柔らかくて電気を通す。エンピツの芯はこの鉱物！" },
  { target: "岩塩", a: "Na", b: "Cl", distractorsA: ["K", "Ca", "Mg"], distractorsB: ["F", "Br", "O"], explanation: "地下の食塩の鉱床。昔の海が干上がった化石みたいな鉱物だ。" },
  { target: "カリ岩塩（シルバイト）", a: "K", b: "Cl", distractorsA: ["Na", "Ca", "Mg"], distractorsB: ["F", "Br", "I"], explanation: "KCl。肥料のカリウム源。バナナが好きな元素を、鉱物から採る！" },
  { target: "蛍石（フローライト）", a: "Ca", b: "F₂", distractorsA: ["Mg", "Ba", "Na"], distractorsB: ["Cl₂", "O₂", "Br₂"], explanation: "製鉄の融剤やフッ酸原料。紫外線で光り、コレクションでも人気No.1級！" },
  { target: "孔雀石（マラカイト）", a: "Cu₂CO₃", b: "(OH)₂", distractorsA: ["CuFeS₂", "Cu₂O", "CuS"], distractorsB: ["SO₄", "Cl₂", "O₂"], explanation: "鮮やかな緑の銅鉱物。古代から顔料や装飾に使われたアート鉱石！" },
  { target: "藍銅鉱（アズライト）", a: "Cu₃(CO₃)₂", b: "(OH)₂", distractorsA: ["Cu₂O", "CuS", "CuFeS₂"], distractorsB: ["SO₄", "Cl₂", "S"], explanation: "深い青の銅炭酸塩。孔雀石とセットで見つかることが多い兄弟鉱物。" },
  { target: "錫石", a: "Sn", b: "O₂", distractorsA: ["Pb", "Zn", "Fe"], distractorsB: ["S", "Cl₂", "CO₃"], explanation: "SnO₂。青銅器時代を支えたスズの源。文明を進めた鉱物！" },
  { target: "ウルツ鉱（閃亜鉛鉱多形）", a: "Zn", b: "S", distractorsA: ["Cd", "Hg", "Fe"], distractorsB: ["O", "Se", "Te"], explanation: "ZnSの別結晶型。同じ組成でも並び方が違うと別鉱物扱いになる不思議。" },
  // —— 反応・精錬 ——
  { target: "銅（還元）", a: "CuO", b: "H₂", distractorsA: ["Cu", "CuS", "CuCl₂"], distractorsB: ["O₂", "Cl₂", "N₂"], explanation: "酸化銅を水素で還元→赤い銅が出現。金属精錬のミニチュア版！" },
  { target: "鉄（高炉イメージ）", a: "Fe₂O₃", b: "C（一酸化炭素）", distractorsA: ["FeS₂", "FeCl₃", "Fe"], distractorsB: ["H₂O", "Cl₂", "N₂"], explanation: "酸化鉄を炭素で還元して鉄に。橋も電車も、この反応の延長線上！" },
  { target: "生石灰", a: "CaCO₃", b: "加熱", distractorsA: ["Ca(OH)₂", "CaCl₂", "CaSO₄"], distractorsB: ["冷却", "加水", "電気分解"], explanation: "石灰石を焼くとCaO＋CO₂。セメント産業のスタートボタン！" },
  { target: "消石灰", a: "CaO", b: "H₂O", distractorsA: ["CaCO₃", "CaCl₂", "Na₂O"], distractorsB: ["CO₂", "HCl", "O₂"], explanation: "生石灰＋水＝消石灰。壁塗りや土壌改良で、暮らしを支える。" },
  { target: "ガラス（イメージ）", a: "SiO₂", b: "Na₂CO₃", distractorsA: ["Fe₂O₃", "CuO", "CaSO₄"], distractorsB: ["NaCl", "HCl", "NH₃"], explanation: "砂＋ソーダ灰＋石灰を溶かして急冷。窓ガラスは高温のアート作品！" },
  { target: "セッケン", a: "油脂", b: "NaOH", distractorsA: ["でんぷん", "たんぱく質", "食塩"], distractorsB: ["HCl", "H₂SO₄", "CO₂"], explanation: "けん化反応！油の汚れを水に流せる分子を手作りする化学。" },
  { target: "エステル（香り分子）", a: "カルボン酸", b: "アルコール", distractorsA: ["塩基", "金属", "塩"], distractorsB: ["酸のみ", "水のみ", "塩のみ"], explanation: "果物のにおいの多くはエステル。実験室でいちご香も作れる！" },
  { target: "メタンハイドレート（イメージ）", a: "CH₄", b: "H₂O（低温高圧）", distractorsA: ["CO₂", "H₂", "N₂"], distractorsB: ["NaCl", "SiO₂", "Fe"], explanation: "燃える氷！海底の低温高圧で水がメタンを閉じ込めた未来燃料候補。" },
  { target: "オゾン層のO₃", a: "O₂", b: "紫外線", distractorsA: ["N₂", "CO₂", "H₂"], distractorsB: ["赤外線", "マイクロ波", "音波"], explanation: "成層圏で酸素が紫外線を受けてオゾンに。日焼けから地球を守る盾！" },
  { target: "塩化カルシウム", a: "Ca", b: "Cl₂", distractorsA: ["Mg", "Ba", "Na"], distractorsB: ["O₂", "F₂", "Br₂"], explanation: "道路の凍結防止剤。水を吸う性質で乾燥剤にもなる実用塩。" },
  { target: "塩化マグネシウム", a: "Mg", b: "Cl₂", distractorsA: ["Ca", "Na", "K"], distractorsB: ["O₂", "F₂", "S"], explanation: "にがりの主成分。豆腐を固めるとき、海のミネラルが活躍！" },
  { target: "硝酸カリウム", a: "K", b: "NO₃⁻", distractorsA: ["Na", "Ca", "Mg"], distractorsB: ["Cl⁻", "SO₄²⁻", "CO₃²⁻"], explanation: "硝石。肥料や黒色火薬の材料。昔の戦争と農業を変えた塩！" },
  { target: "硫酸アンモニウム", a: "NH₃", b: "H₂SO₄", distractorsA: ["N₂", "NO₂", "H₂"], distractorsB: ["HCl", "HNO₃", "H₂O"], explanation: "硫安肥料。葉っぱを青々させる窒素を、畑に届ける化合物。" },
  { target: "硝酸アンモニウム", a: "NH₃", b: "HNO₃", distractorsA: ["N₂", "NO", "H₂"], distractorsB: ["HCl", "H₂SO₄", "H₂O"], explanation: "肥料でもあり扱いに注意な化合物。窒素をドカッと含む。" },
  { target: "炭酸カルシウム（鍾乳石）", a: "Ca²⁺", b: "CO₃²⁻", distractorsA: ["Na⁺", "K⁺", "Fe²⁺"], distractorsB: ["Cl⁻", "SO₄²⁻", "OH⁻"], explanation: "鍾乳洞の石のカーテン。何百年もかけて垂れる水滴が彫刻する！" },
  { target: "シリカゲル", a: "SiO₂", b: "nH₂O", distractorsA: ["NaCl", "CaCl₂", "Al₂O₃"], distractorsB: ["油", "アルコール", "酸"], explanation: "お菓子の袋に入ってる「食べられません」粒。湿気を吸う乾燥の番人。" },
  { target: "セメントの原料（石灰石＋粘土）", a: "CaCO₃", b: "Al₂O₃・SiO₂", distractorsA: ["NaCl", "FeS₂", "CuFeS₂"], distractorsB: ["H₂Oのみ", "NaOH", "HCl"], explanation: "石灰石と粘土を焼いてクリンカに。ビルも橋も、鉱物ミックスの力！" },
  { target: "陶器の釉薬イメージ", a: "SiO₂", b: "金属酸化物", distractorsA: ["NaCl", "砂糖", "油脂"], distractorsB: ["水素", "窒素", "ヘリウム"], explanation: "釉薬の色は金属酸化物のおかげ。銅で赤、鉄で茶、化学が絵の具！" },
  { target: "フェライト磁石", a: "Fe₂O₃", b: "MO（金属酸化物）", distractorsA: ["CuO", "NaCl", "SiO₂"], distractorsB: ["H₂", "Cl₂", "CO₂"], explanation: "スピーカーや磁石シートの中身。酸化鉄が磁気のヒーロー！" },
  { target: "ステンレス（イメージ）", a: "Fe", b: "Cr・Ni", distractorsA: ["Cu", "Zn", "Pb"], distractorsB: ["S", "P", "Cl₂"], explanation: "クロムが表面に酸化皮膜を作りさびを防ぐ。キッチンの銀色の秘密。" },
  { target: "青銅", a: "Cu", b: "Sn", distractorsA: ["Fe", "Zn", "Pb"], distractorsB: ["O₂", "S", "Cl₂"], explanation: "銅＋スズ＝青銅。銅器時代を終わらせた合金革命！" },
  { target: "黄銅（真鍮）", a: "Cu", b: "Zn", distractorsA: ["Sn", "Fe", "Ni"], distractorsB: ["O₂", "S", "Cl₂"], explanation: "銅＋亜鉛で金色っぽく。楽器やドアノブのあの色！" },
  { target: "はんだ", a: "Sn", b: "Pb（伝統）", distractorsA: ["Fe", "Cu", "Al"], distractorsB: ["Zn", "Ni", "Cr"], explanation: "融点が低く電子工作で大活躍。今は鉛フリーも主流！" },
  { target: "消火器のCO₂", a: "炭酸水素塩", b: "酸", distractorsA: ["金属", "塩基", "塩だけ"], distractorsB: ["塩基", "金属", "水だけ"], explanation: "酸と炭酸水素塩でCO₂発生→酸素を押しのけて火を消す。化学反応のヒーロー消火！" },
  { target: "石灰水の沈殿", a: "Ca(OH)₂", b: "CO₂", distractorsA: ["NaOH", "KOH", "Ba(OH)₂"], distractorsB: ["O₂", "H₂", "N₂"], explanation: "呼気中のCO₂検出。白濁したら「息に炭素がいた！」の証拠。" },
  { target: "アルミニウムの精錬（ホール・エルー）", a: "Al₂O₃", b: "電気分解", distractorsA: ["Al", "AlCl₃", "Al(OH)₃"], distractorsB: ["加熱のみ", "還元剤のみ", "ろ過"], explanation: "溶融塩電解でアルミを取り出す。電気をたくさん使うからリサイクルが大事！" },
  { target: "塩素酸カリウムから酸素", a: "KClO₃", b: "MnO₂", distractorsA: ["KCl", "KNO₃", "NaCl"], distractorsB: ["Fe₂O₃", "CuO", "CaCO₃"], explanation: "加熱＋触媒で酸素発生。ただし危険な実験なので、先生の指示が絶対！" },
  { target: "硫化水素（実験室）", a: "FeS", b: "HCl", distractorsA: ["Fe₂O₃", "Fe", "FeCl₃"], distractorsB: ["H₂SO₄", "HNO₃", "H₂O"], explanation: "硫化鉄に酸で卵臭ガス。火山や温泉のにおいラボ版。" },
  { target: "二酸化硫黄（燃焼）", a: "S", b: "O₂", distractorsA: ["P", "C", "N₂"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "硫黄を燃やすと刺激臭。酸性雨の原因物質のひとつでもある。" },
  { target: "五酸化二リン", a: "P₄", b: "O₂", distractorsA: ["N₂", "S₈", "C"], distractorsB: ["H₂", "Cl₂", "N₂"], explanation: "リンの激しい燃焼で白煙。強力な乾燥剤P₄O₁₀の原料！" },
  { target: "ヨウ素デンプン反応（青紫）", a: "I₂", b: "デンプン", distractorsA: ["Cl₂", "Br₂", "F₂"], distractorsB: ["砂糖", "油脂", "たんぱく質"], explanation: "ごはんにヨウ素液で青紫。炭水化物探偵の決め手反応！" },
  { target: "銀鏡反応の銀", a: "Ag⁺", b: "還元性糖", distractorsA: ["Cu²⁺", "Fe³⁺", "Na⁺"], distractorsB: ["食塩", "デンプン", "油脂"], explanation: "試験管の内側が鏡に！アルデヒドが銀イオンを還元する美しい実験。" },
  { target: "フェーリング液の赤沈殿", a: "Cu²⁺", b: "還元性糖", distractorsA: ["Fe³⁺", "Ag⁺", "Zn²⁺"], distractorsB: ["デンプン", "油脂", "食塩"], explanation: "青い液が加熱で赤レンガ色に。糖の検出、化学探偵の名刺代わり。" },
  { target: "ナイロン（イメージ）", a: "ジアミン", b: "ジカルボン酸", distractorsA: ["金属", "塩", "糖"], distractorsB: ["アルコールのみ", "水のみ", "酸のみ"], explanation: "界面で糸が引ける高分子。ストッキングもロープも、分子の長〜い鎖！" },
  { target: "ポリエチレン", a: "C₂H₄", b: "重合", distractorsA: ["CH₄", "C₂H₂", "C₆H₆"], distractorsB: ["分解", "中和", "沈殿"], explanation: "エチレンが繋がってビニール袋に。身の回りのプラスチックの代表格。" },
  { target: "塩化ビニル樹脂", a: "C₂H₃Cl", b: "重合", distractorsA: ["C₂H₄", "CH₄", "C₆H₆"], distractorsB: ["中和", "還元", "酸化のみ"], explanation: "塩ビパイプの材料。モノマーが繋がると硬い建材に変身！" },
  { target: "尿素", a: "NH₃", b: "CO₂", distractorsA: ["N₂", "NO₂", "H₂"], distractorsB: ["O₂", "H₂", "Cl₂"], explanation: "肥料やプラスチック原料。体の中でもタンパク質代謝で作られる！" },
  { target: "炭酸カルシウム（貝殻）", a: "Ca²⁺", b: "CO₃²⁻", distractorsA: ["Na⁺", "K⁺", "Mg²⁺のみ"], distractorsB: ["Cl⁻", "SO₄²⁻", "PO₄³⁻"], explanation: "貝殻・卵の殻・サンゴ。海の生き物は鉱物を体で作るプロだ！" },
  { target: "アパタイト（骨の鉱物）", a: "Ca₅(PO₄)₃", b: "(OH,F,Cl)", distractorsA: ["CaCO₃", "SiO₂", "Fe₂O₃"], distractorsB: ["SO₄", "NO₃", "S"], explanation: "歯や骨の硬さの正体。リン灰石は体の中の鉱物コレクション！" },
  { target: "黄玉（トパーズ再）", a: "Al₂SiO₄", b: "(F,OH)₂", distractorsA: ["Be₃Al₂Si₆O₁₈", "Al₂O₃", "SiO₂"], distractorsB: ["Cl₂", "Br₂", "I₂"], explanation: "硬い・美しい・フッ素入り。宝石箱と周期表がつながる瞬間！" },
  { target: "ラピスラズリ（群青）", a: "藍方石など", b: "（複合鉱物）", distractorsA: ["石英のみ", "方解石のみ", "黄鉄鉱のみ"], distractorsB: ["単体硫黄", "純銅", "純鉄"], explanation: "古代の最高級青顔料。ツタンカーメンも使った、鉱物のロイヤルブルー！" },
  { target: "トルコ石", a: "CuAl₆", b: "(PO₄)₄(OH)₈・4H₂O", distractorsA: ["CuFeS₂", "Cu₂O", "CuCO₃"], distractorsB: ["SO₄", "Cl₂", "S"], explanation: "空色のリン酸塩鉱物。ジュエリーの定番で、銅が青い色を演出！" },
  { target: "翡翠（ヒスイ輝石）", a: "NaAl", b: "Si₂O₆", distractorsA: ["CaMg", "Fe₃Al₂", "Mg₃"], distractorsB: ["CO₃", "SO₄", "O₂"], explanation: "東アジアで宝とされた硬玉。ケイ酸塩の美しさが文化を動かした！" },
  { target: "黒曜石", a: "SiO₂", b: "急冷火山ガラス", distractorsA: ["FeS₂", "CaCO₃", "NaCl"], distractorsB: ["徐冷結晶", "水溶液", "金属融解"], explanation: "溶岩が急に冷えてガラスに。切れ味鋭い石器の材料だった天然ガラス！" },
  { target: "軽石", a: "火山ガス", b: "ケイ酸質マグマ", distractorsA: ["海水", "石灰", "鉄"], distractorsB: ["花崗岩", "岩塩", "石炭"], explanation: "穴だらけで水に浮く石。お風呂のかかとすりも、火山のプレゼント！" },
  { target: "玄武岩のかんらん石", a: "マグマ", b: "Mg・Feケイ酸塩", distractorsA: ["海水のみ", "石灰岩のみ", "大気のみ"], distractorsB: ["純金", "岩塩", "石炭"], explanation: "黒い火山岩の中に黄緑の粒。マントルのかけらが地面に来た証拠！" },
  { target: "石灰岩", a: "生物殻", b: "CaCO₃堆積", distractorsA: ["溶岩", "砂だけ", "塩だけ"], distractorsB: ["SiO₂のみ", "Fe₂O₃のみ", "Cのみ"], explanation: "昔の海の生き物が積み重なって山に。セメントの原料山もこれ！" },
  { target: "大理石", a: "石灰岩", b: "変成作用", distractorsA: ["砂岩", "頁岩", "花崗岩"], distractorsB: ["溶解のみ", "蒸発のみ", "電解析出"], explanation: "石灰岩が熱と圧力で生まれ変わる。彫刻や建物の白い高級石！" },
  { target: "粘板岩", a: "泥岩", b: "変成作用", distractorsA: ["石灰岩", "砂岩", "れき岩"], distractorsB: ["急冷", "蒸発", "生物堆積のみ"], explanation: "黒板や屋根材になった石。泥が圧力でピシッと割れる性質に！" },
  { target: "花崗岩", a: "マグマ（Si多い）", b: "ゆっくり冷却", distractorsA: ["溶岩急冷", "海の蒸発", "生物殻"], distractorsB: ["超急冷", "水溶液沈殿", "衝撃変成のみ"], explanation: "地上の頑丈石。石英・長石・雲母の集合体で、ビルの外壁にも多い。" },
  { target: "サファイア", a: "Al₂O₃", b: "Fe・Ti不純物", distractorsA: ["SiO₂", "Be₃Al₂Si₆O₁₈", "CaCO₃"], distractorsB: ["Crのみ", "Cuのみ", "純金"], explanation: "コランダム＋不純物で青に。同じ鉱物で赤ならルビー、色で名前が変わる！" },
  { target: "ルビー", a: "Al₂O₃", b: "Cr不純物", distractorsA: ["SiO₂", "Fe₂O₃", "Cu₂O"], distractorsB: ["Fe・Ti", "Cu", "Ni"], explanation: "クロムが赤を作るコランダム。王者の赤は、微量元素の魔法！" },
  { target: "琥珀（こはく）", a: "樹脂", b: "化石化", distractorsA: ["マグマ", "海水塩", "金属"], distractorsB: ["急冷ガラス", "変成だけ", "電解析出"], explanation: "木の樹脂が何千万年。中に虫が入った標本はタイムカプセル鉱物（厳密には鉱物ではないが宝物！）。" },
  { target: "石炭", a: "植物", b: "炭化・圧密", distractorsA: ["マグマ", "海水", "金属鉱液"], distractorsB: ["急冷", "蒸発岩化", "衝撃変成のみ"], explanation: "太古の森が地下で炭素リッチに。火力の陰に、植物の化石エネルギー。" },
  { target: "石油のもと（イメージ）", a: "プランクトン等", b: "熱・圧力", distractorsA: ["花崗岩", "岩塩だけ", "純鉄"], distractorsB: ["太陽光だけ", "電気分解", "ろ過だけ"], explanation: "海の微生物が長い年月で炭化水素に。クルマの燃料も地球史の産物！" },
  { target: "天然ガス（主成分メタン）", a: "CH₄", b: "（貯留）", distractorsA: ["CO₂", "H₂", "O₂"], distractorsB: ["液体化必須", "金属化", "結晶化必須"], explanation: "コンロの火の主成分。クリーンめに燃える化石燃料の代表。" },
  { target: "消石灰モルタル", a: "Ca(OH)₂", b: "CO₂", distractorsA: ["CaCl₂", "NaOH", "KOH"], distractorsB: ["O₂", "H₂", "N₂"], explanation: "壁が固まるとき空気のCO₂を吸う。建物が呼吸して石に戻る化学！" },
  { target: "コンクリート", a: "セメント", b: "水・骨材", distractorsA: ["砂だけ", "鉄だけ", "木だけ"], distractorsB: ["油", "アルコール", "酸だけ"], explanation: "セメントの水和反応でガチガチに。現代都市を支える最大の人造石！" },
  { target: "水素燃料電池の水", a: "H₂", b: "O₂", distractorsA: ["N₂", "CO₂", "Cl₂"], distractorsB: ["N₂", "CO₂", "Cl₂"], explanation: "燃やすのではなく発電して水が出る。未来のクルマの排気は水滴！？" },
  { target: "漂白粉の有効塩素", a: "Ca(ClO)₂", b: "（次亜塩素酸系）", distractorsA: ["NaCl", "CaCl₂", "CaCO₃"], distractorsB: ["純酸素", "窒素", "水素"], explanation: "プールや消毒の白さ＆におい。塩素化学が衛生を守る！" },
  { target: "ホウ砂ビーズ（イメージ）", a: "ホウ砂", b: "金属酸化物", distractorsA: ["食塩", "砂糖", "石膏"], distractorsB: ["水素", "窒素", "ヘリウム"], explanation: "炎色やビーズの色で金属を当てる古典分析法。色で元素を見抜く！" },
];

// 完成形のみの問題は a を正解、b は「（完成形）」等を選ばせる教育用
// チェック時は a/b の順序不問、文字列完全一致

function getQuizBank(level) {
  return level === "junior" ? QUIZ_JUNIOR : QUIZ_ELEMENTARY;
}
